const CONSTANTS = {
    TASK_ADD__MODAL: 'TASK_ADD__MODAL',
    TASK_DELETE__MODAL: 'TASK_DELETE__MODAL',
    TASK_EDIT__MODAL: 'TASK_EDIT__MODAL',
    TASK_VIEW__MODAL: 'TASK_VIEW__MODAL',
};

export default CONSTANTS;